
import java.util.*;
import java.util.Random;


class Main
{
     public static void main(String[] args) {
        int iret=0;
        int sucess=0;   //initialize sucess rate as 0
        
        Scanner sc=new Scanner(System.in);
        System.out.println("Welcome to Guess the number Game!!");
        System.out.println("Enter a number:");  //taking input from user
        int no=sc.nextInt();
        Game gm=new Game();
        gm.takeUserInput(no);

        
        int ran_no=gm.random_Return();  //accessing random integer generated by computer from another class 
        
        while(no!=ran_no)
        {
        
        iret=gm.isCorrectNumber(no); //accessing iret value i.e 1/2 or 3
        
       if(iret==2)
        {
            sucess++;
            System.out.println("Sorry the number you entered is greater than random number try again and enter a new number!");
            int no1=sc.nextInt();
            iret=gm.isCorrectNumber(no1);     //logic//
            no=no1;
            continue;

        }
        else if(iret==3)
        {
            sucess++;
            System.out.println("Sorry  the number you entered is smaller than random number try again and enter a new number!");
            int no2=sc.nextInt();
            iret=gm.isCorrectNumber(no2);
            no=no2;
            continue;
        }
         
    }
    if(iret==1)
    {
        sucess++;
        System.out.println("You win!");
        System.out.println("Your sucess is:"+sucess);
        
    }
}
}

class Game
{
    int ran_no;
    int sucess;
    
    public  Game()
    {
     Random ram=new Random();
     ran_no=ram.nextInt(100);
     
    }
    public int random_Return()
    {
        return ran_no;
    }
    public void takeUserInput(int no)
    {
     int num;
     
     num=no;
     System.out.println("You entered a number:"+num);
    }
    public int isCorrectNumber(int no)
    {
        if(ran_no==no)
        {
          return 1;
        }
       else if(no>ran_no)
       {
        
        return 2;
        
       }
       else
       {
        
        return 3;
       }

        
    }

   
}

